### PR TITLE
Remove the explicit version from the composer.json

### PR DESCRIPTION
**Pull request by stof**
Explicit version are useless when the package is in a Git repository, but they can be harmful:

- the version is ignored entirely for branches (branch aliases are available instead)
- the version can make tags invalid if it does not match the version defined by the tag name

### CODE REVIEW

**Comment by ve3** [comment]
Hello. 

Thanks for contributing to the project. 
But, I'm really do not understand about what you are saying.
Can you please describe more details about this? I'm not good about Composer/Packagist too. I don't familiar with it, mostly I just use it.
Or may I remove all tag/release version and set to the correct name? (And how to correct it?)

You can reply me via email kawewong@gmail.com :)

**Comment by stof** [comment]
@ve3 when the package is in a VCS repository (Git, SVN, Hg or Perforce), Composer relies on the VCS metadata to build the metadata of the versions. This means that the version for tags is guessed based on the tag name.
Putting an explicit version in the composer.json in such packages only creates issues. The rule is simple: never put the ``version`` in your composer.json (the cases where you actually need to put it are quite edge cases, so it is safe to avoid considering it)

**Comment by stof** [comment]
and this will avoid having issues like https://github.com/composer/packagist/issues/605 in the future

**Comment by ve3** [comment]
Thanks a lot :D :+1:

**Pull request merged**
